// <auto-generated />
namespace Exam_ExampleForTest_17_01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TheGuestsTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TheGuestsTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202201170839579_TheGuestsTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
